version: 2.1
orbs:
  docker: circleci/docker@1.3.0
jobs:
  build_app:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: |
                set -xu
                mkdir -p project/artifacts
                cp target/*.jar project/artifacts
      - run: |
                set -xu
                cp Dockerfile project
      - persist_to_workspace:
          root: .
          paths:
            - project
      - store_artifacts:
          path: project/artifacts
  build_container:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_app
      - docker/publish:
          requires:
            - build_app
          image: mattbrabazon/circleci-demo
          attach-at: .
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
