version: 2
jobs:
  build_app:
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
      - persist_to_workspace:
          root: workspace
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_app
      - build_container:
          requires:
            - build_app
